version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      - "3305:3306"
    networks:
      - lumen_test
    volumes:
      - ./backups/:/backups/
      - ./docker/mysql/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=project
      - MYSQL_USER=developer
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password

  php-fpm:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
      args:
        environment: dev
    volumes:
      - ./:/usr/src/app
      - "~/.composer.sh:/root/.composer.sh"
      - "~/.ssh:/root/.ssh-local:ro"
    networks:
      - lumen_test
    depends_on:
      - mysql
    environment:
      - LOCAL_ENV=1
      - COMPOSER_ALLOW_SUPERUSER=1
      - DB_HOST=mysql
      - DB_DATABASE=project
      - DB_USERNAME=developer
      - DB_PASSWORD=password
      - PHP_IDE_CONFIG=serverName=docker
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "11150:80"
    networks:
      - lumen_test
    depends_on:
      - php-fpm




networks:
  lumen_test:
      external: true
